os:
  - linux

language: php

php:
  - '7.2'

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database db_laravel_test;'
  - composer self-update
  - composer install --no-interaction'



script:
  - php artisan config:clear
  - php artisan cache:clear
  - php artisan key:generate
  - php artisan migrate --seed
  - vendor/bin/phpunit tests/Unit/demo.php





