os:
  - linux

language: php

php:
  - '7.2'

services:
  - mysql

before_script:
  - composer self-update
  - composer install --no-interaction


script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - vendor/bin/phpunit tests/Unit/demo.php

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client


before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_laravel_test;'
  - sudo service mysql restart
